# Generated by Django 5.2.17 on 2026-09-14 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_education'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='subtitle',
            new_name='institution',
        ),
        migrations.RenameField(
            model_name='education',
            old_name='title',
            new_name='program',
        ),
        migrations.AddField(
            model_name='education',
            name='level',
            field=models.CharField(choices=[('grade_school', 'Grade School'), ('junior_high_school', 'Junior High School'), ('high_school', 'High School'), ('undergraduate', 'Undergraduate'), ('graduate', 'Graduate')], default='undergraduate', max_length=20),
        ),
    ]
